service: projeto

provider:
  name: offline
  runtime: nodejs12.x
  apiKeys:
    - minhaChaveSecreta
plugins:
  - serverless-offline
functions:
  obterTodos:
    handler: handler.obterTodos
    events:
      - http:
          path: usuarios
          method: get
          private: true
  obter:
    handler: handler.obter
    events:
      - http: 
          path: usuarios/{id}
          method: get
          private: true
          request: 
            parameters: 
                paths: 
                  id: true
  criar:
    handler: handler.criar
    events:
      - http:
          path: usuarios
          method: post
          private: true
